cache_variable_dict = {
    'composition': 'Доступные ГРС',
    'temperature': 'Температура, °С',
    'alpha': 'Коэффициент расхода',
    'valve_area': 'Площадь седла, мм',
    'rate': 'Расход, ст. м3/ч',
    'capacity_mass': 'Расход, кг/ч',
    'capacity_normal': 'Расход, нм3/ч',
    'capacity_standard': 'Расход, ст.м3/ч',
    'pressure': 'Давление, МПа',
    'diameter': 'Внешний диаметр, мм',
    'wall': 'Толщина стенки, мм',
    'pipe_velocity': 'Скорость газа',
    'normal_density': 'Плотность при н.у.',
    'standard_density': 'Плотность при ст.у.',
    'volume': 'Вместимость ёмкости',
    'odorant_request': 'Необходимый объем одоранта',
    'kv': 'Kv, м3/ч',
    'inlet_pressure': 'Давление до клапана, МПа',
    'outlet_pressure': 'Давление после клапана, МПа',
}
