# Файл с декларативным описанием привязок интерфейса к программной логике.
# Здесь описываются заполнение screen'а текстовыми полями, метками, привязками полей ввода к переменным, привязками кнопок и событий к долбежкам(функциям)
#
#- screen:
#    Обозначает шаблон, к виджета которого надо привязываться
#    Описание шаблонов хранится в файле template_config.yml
#
#
#- widgets(виджеты):
#  Типы виджетов:
#    - entry:
#        Описывает переменную, для которой нужно создать поле ввода
#        Список встроенных переменных хранится в БД в таблице 'quantity'
#
#    - combobox:
#        Описывает переменную, для которых нужно создать выбор из списка
#        Список встроенных переменных хранится в БД в таблице 'combobox'
#        Поддерживает настройку:
#        - values : колбэк для заполнения списка комбобокса. Для встроенных переменных описан в таблице 'combobox'
#        - selected : колбэк, вызываемый при выборе значения из списка
#
#    - button:
#        Описывает колбэк, вызываемой при нажатии на кнопку ЛКМ
#
#  Блоки:
#    Виджеты группируются в блоки
#    Для корректного связывания с ГУИ названия блоков должны совпадать
#      с названиями блоков ($block, $grid и т.д.) из соответствующего screen'а в template_config.yml
#    Каждый блок поддерживает параметр values.
#      - values : Описывает колбэк, возвращающий список значений для блока. Используется для автогенерации
#    Названия блоков из template_config.yml могут быть опущены, тогда соответствующий блок не будет создан
#
#
#Префиксы:
#  Уточняют, откуда берутся переменные и колбэки
#  В рамках одного префикса название должно быть уникальным
#
#- Для переменных:
#  - без префикса : значение берется из дефолтного хранилища
#  - $custom : новая временная переменная в рамках заданного экрана

#- Для колбэков:
#  - $window : колбэк графического интерфейса (обновить гуи, отрисовать другой экран итд)
#  - $db : колбэк базы данных (запрос для списков комбобоксов, датафреймов pandas, для графиков итд)
#  - $cache : аналогичен $db, но сначала проверяет нужные значения в кэше. Используется для подтягивания статичной информации
#  - $logic : колбэк бизнес-логики (расчет физических функций)
#  - $meta : программные мета-функции (получение списка аргументов)
#  - $custom : новый временный колбэк ???в рамках заданного экрана???
#
#  '__{имя}' : нереализованная переменная или колбэк


Главное меню:
  screen: menu
  widgets:
    button:
      values: $meta.get_move_to_screen_callbacks

Расчет скорости в трубопроводах:
  screen: calculator
  widgets:
    combobox:
    - composition
    entry:
    - pressure
    - temperature
    - rate
    - diameter
    - wall
    button:
    - __Подбор диаметра
    - $logic.calc_gas_density
    - $logic.calc_pipe_velocity

Ёмкость одоранта:
  screen: calculator
  widgets:
    entry:
    - rate
    - volume
    button:
    - $logic.calc_odorant_reserve
    - $logic.calc_odorant_volume_request

Пропускная способность клапанов:
  screen: calculator
  widgets:
    combobox:
    - composition
    entry:
    - kv
    - inlet_pressure
    - outlet_pressure
    - temperature
    - rate
    button:
    - __Полный расчёт
    - $logic.calc_valve_kv
    - $logic.calc_valve_capacity

Расчет подогревателя газа:
  screen: calculator
  widgets:
    combobox:
    - composition
    entry:
    - rate
    - __Давление на входе ГРС, МПа
    - __Давление на выходе ГРС, МПа
    - __Температура газа на входе ГРС, °С
    - __Минимальная тем-ра на выходе, °С
    button:
    - __Выполнить расчёт

Расчёт предохранительных клапанов:
  screen: calculator
  widgets:
    combobox:
    - composition
    entry:
    - inlet_pressure
    - temperature
    - alpha
    - valve_area
    - rate
    button:
    - $logic.calc_capacity_ppk
    - $logic.calc_valve_area_ppk

Расчёт ТВПС:
  screen: calculator
  widgets:
    combobox:
    - composition
    entry:
    - __Минимальное давление
    - __Максимальное давление
    - __Шаг по давлению
    - __Минимальная температура
    - __Максимальная температура
    - __Число точек по температуре
    - __Масштаб подписей данных
    button:
    - __Таблица
    - __Расчёт
    - __Вставить секцию ТВПС
    - __График ТВПС
    - __Показать ТВПС

Толщина стенок трубопроводов: null

Схема: null

Статистика:
  screen: statistic
  widgets:
    combobox:
    - composition:
        selected:
        - $window.update_outlet_combobox
        - $window.draw_plot
    - outlet:
        selected: $window.draw_plot
    - quantity:
        selected: $window.draw_plot

База данных ГРС: null